export const nigerianBanks = [
  { name: 'Access Bank', code: '044' },
  { name: 'Citibank', code: '023' },
  { name: 'Ecobank Nigeria', code: '050' },
  { name: 'Fidelity Bank Nigeria', code: '070' },
  { name: 'First Bank of Nigeria', code: '011' },
  { name: 'First City Monument Bank', code: '214' },
  { name: 'Globus Bank', code: '00103' },
  { name: 'Guaranty Trust Bank', code: '058' },
  { name: 'Heritage Bank Plc', code: '030' },
  { name: 'Jaiz Bank', code: '301' },
  { name: 'Keystone Bank Limited', code: '082' },
  { name: 'Kuda Bank', code: '50211' },
  { name: 'Parallex Bank', code: '526' },
  { name: 'Polaris Bank', code: '076' },
  { name: 'Providus Bank Plc', code: '101' },
  { name: 'Stanbic IBTC Bank Nigeria Limited', code: '221' },
  { name: 'Standard Chartered Bank', code: '068' },
  { name: 'Sterling Bank', code: '232' },
  { name: 'Suntrust Bank Nigeria Limited', code: '100' },
  { name: 'TAJBank', code: '302' },
  { name: 'Titan Trust Bank', code: '102' },
  { name: 'Union Bank of Nigeria', code: '032' },
  { name: 'United Bank for Africa', code: '033' },
  { name: 'Unity Bank Plc', code: '215' },
  { name: 'Wema Bank', code: '035' },
  { name: 'Zenith Bank', code: '057' },
  { name: 'Opay', code: '999992' },
  { name: 'PalmPay', code: '999991' },
  { name: 'Moniepoint', code: '50515' },
  { name: 'First City Monument Bank (FCMB)', code: '214' },
  { name: 'Guaranty Trust Bank (GTBank)', code: '058' },
  { name: 'United Bank for Africa (UBA)', code: '033' },
  { name: 'Kuda Microfinance Bank', code: '50211' },
  { name: 'FairMoney Microfinance Bank', code: '' },
  { name: 'Moniepoint Microfinance Bank', code: '50515' },
  { name: 'Opay Microfinance Bank', code: '999992' },
  { name: 'Opay Microfinance Bank Ltd', code: '999992' },
  { name: 'RenMoney (Rencredit) Microfinance Bank', code: '' },
  { name: 'Pillar Microfinance Bank', code: '' },
  { name: 'Mutual Benefits Microfinance Bank', code: '' },
  { name: 'Main Trust Microfinance Bank', code: '' },
  { name: 'Ngala Microfinance Bank', code: '' },
  { name: 'Borno Renaissance Microfinance Bank', code: '' },
];
