-- AlterTable
ALTER TABLE "RiderProfile" ADD COLUMN     "balance" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Store" ADD COLUMN     "balance" DOUBLE PRECISION NOT NULL DEFAULT 0;
