
ALTER TABLE "Ride" ADD COLUMN IF NOT EXISTS "assignedBy" TEXT;
ALTER TABLE "Ride" ADD COLUMN IF NOT EXISTS "assignmentWindowMin" INTEGER DEFAULT 90;
ALTER TABLE "Ride" ADD COLUMN IF NOT EXISTS "cancellationDeadline" TIMESTAMP(3);
ALTER TABLE "Ride" ADD COLUMN IF NOT EXISTS "estimatedDurationMin" INTEGER;
ALTER TABLE "Ride" ADD COLUMN IF NOT EXISTS "estimatedEndTime" TIMESTAMP(3);
ALTER TABLE "Ride" ADD COLUMN IF NOT EXISTS "isScheduled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Ride" ADD COLUMN IF NOT EXISTS "lateCancellation" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Ride" ADD COLUMN IF NOT EXISTS "scheduledAt" TIMESTAMP(3);
ALTER TABLE "Ride" ADD COLUMN IF NOT EXISTS "scheduledFare" DOUBLE PRECISION;
