import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { OpaqueColorValue, type StyleProp, type TextStyle } from "react-native";

/**
 * An icon symbol using MaterialIcons on Android and iOS.
 * Maps SF Symbol-style names to MaterialIcons.
 */
export type IconSymbolName =
  | "house.fill"
  | "eye"
  | "doc.on.doc"
  | "clock"
  | "exclamationmark.octagon"
  | "doc"
  | "ticket.fill"
  | "fork.knife"
  | "chart.line.uptrend.xyaxis"
  | "person.crop.circle.fill"
  | "eye.fill"
  | "eye.slash.fill"
  | "paperplane.fill"
  | "chevron.left.forwardslash.chevron.right"
  | "chevron.right"
  | "chevron.left"
  | "chevron.down"
  | "chevron.up"
  | "info.circle"
  | "cloud.upload"
  | "cloud.fill"
  | "camera.fill"
  | "check"
  | "circle.fill"
  | "car.fill"
  | "mappin.circle.fill"
  | "map.marker"
  | "location.fill"
  | "arrow.up.left.and.arrow.down.right"
  | "xmark"
  | "map.fill"
  | "lock.fill"
  | "pencil"
  | "trash"
  | "plus"
  | "fullscreen"
  | "send"
  | "home"
  | "restaurant"
  | "notifications"
  | "logout"
  | "chat"
  | "icon"
  | "menu"
  | "users"
  | "power"
  | "arrow.right"
  | "arrow.left"
  | "arrow-left"
  | "arrow-right"
  | "arrow-u-turn-left"
  | "arrow-u-turn-right"
  | "arrow.up"
  | "arrow-upward"
  | "settings"
  | "bell"
  | "list"
  | "dollar-sign"
  | "info"
  | "headphones"
  | "play"
  | "activity"
  | "lightbulb"
  | "shield"
  | "close"
  | "edit"
  | "delete"
  | "add"
  | "share"
  | "file-text"
  | "credit-card"
  | "alert-circle"
  | "calender"
  | "clock.fill"
  | "touchid"
  | "1.circle.fill"
  | "2.circle.fill"
  | "checkmark.circle.fill"
  | "circle"
  | "arrow.down"
  | "location.on"
  | "map"
  | "storefront"
  | "person.circle"
  | "bag"
  | "package"
  | "arrow.clockwise"
  | "pizza"
  | "p.square"
  | "d.square"
  | "arrow.right.circle"
  | "note"
  | "phone"
  | "checkmark"
  | "navigation"
  | "person"
  | "checkmark.seal"
  | "star.fill"
  | "person.text.rectangle"
  | "doc.text"
  | "creditcard"
  | "car"
  | "box.truck"
  | "shippingbox.fill"
  | "calendar"
  | "exclamationmark.triangle"
  | "exclamationmark.triangle.fill"
  | "info.circle.fill"
  | "checkmark.seal.fill"
  | "exclamationmark.octagon.fill"
  | "doc.fill"
  | "doc.on.doc.fill"
  | "hand.raised.fill"
  | "pause.circle.fill"
  | "list.clipboard.fill";

const MAPPING: Record<IconSymbolName, keyof typeof MaterialIcons.glyphMap> = {
  "house.fill": "home",
  eye: "remove-red-eye",
  "doc.on.doc": "library-books",
  clock: "access-time",
  "exclamationmark.octagon": "report-problem",
  doc: "description",
  "ticket.fill": "confirmation-number",
  "fork.knife": "restaurant",
  "chart.line.uptrend.xyaxis": "show-chart",
  "person.crop.circle.fill": "account-circle",
  "eye.fill": "visibility",
  "eye.slash.fill": "visibility-off",
  "paperplane.fill": "send",
  "chevron.left.forwardslash.chevron.right": "code",
  "chevron.right": "chevron-right",
  "chevron.left": "chevron-left",
  "chevron.down": "keyboard-arrow-down",
  "chevron.up": "keyboard-arrow-up",
  "info.circle": "info",
  "info.circle.fill": "info",
  "cloud.upload": "cloud-upload",
  "cloud.fill": "cloud",
  "camera.fill": "photo-camera",
  check: "check",
  "circle.fill": "circle",
  "car.fill": "directions-car",
  "mappin.circle.fill": "location-on",
  "map.marker": "place",
  "location.fill": "location-on",
  "arrow.up.left.and.arrow.down.right": "fullscreen",
  xmark: "close",
  "map.fill": "map",
  "lock.fill": "lock",
  pencil: "edit",
  trash: "delete",
  plus: "add",
  fullscreen: "fullscreen",
  send: "send",
  home: "home",
  restaurant: "restaurant",
  notifications: "notifications",
  logout: "logout",
  chat: "chat",
  icon: "help",
  menu: "menu",
  users: "people",
  power: "power",
  "arrow.right": "arrow-forward",
  "arrow.left": "arrow-back",
  "arrow-left": "arrow-back",
  "arrow-right": "arrow-forward",
  "arrow-u-turn-left": "settings-backup-restore",
  "arrow-u-turn-right": "redo",
  "arrow.up": "arrow-upward",
  "arrow-upward": "arrow-upward",
  settings: "settings",
  bell: "notifications",
  list: "list",
  "dollar-sign": "attach-money",
  info: "info",
  headphones: "headset",
  play: "play-arrow",
  activity: "show-chart",
  lightbulb: "lightbulb",
  shield: "security",
  close: "close",
  edit: "edit",
  delete: "delete",
  add: "add",
  share: "share",
  "file-text": "description",
  "credit-card": "credit-card",
  "alert-circle": "error-outline",
  calender: "calendar-today",
  "clock.fill": "access-time",
  touchid: "fingerprint",
  "1.circle.fill": "looks-one",
  "2.circle.fill": "looks-two",
  "checkmark.circle.fill": "check-circle",
  circle: "radio-button-unchecked",
  "arrow.down": "arrow-downward",
  "location.on": "location-on",
  map: "map",
  storefront: "store",
  "person.circle": "account-circle",
  bag: "local-mall",
  package: "inventory",
  "arrow.clockwise": "refresh",
  pizza: "local-pizza",
  "p.square": "local-parking",
  "d.square": "directions",
  "arrow.right.circle": "arrow-circle-right",
  note: "note",
  phone: "phone",
  checkmark: "check",
  navigation: "navigation",
  person: "person",
  "checkmark.seal": "verified",
  "checkmark.seal.fill": "verified",
  "star.fill": "star",
  "person.text.rectangle": "badge",
  "doc.text": "article",
  creditcard: "credit-card",
  car: "directions-car",
  "box.truck": "local-shipping",
  "shippingbox.fill": "unarchive",
  calendar: "calendar-today",
  "exclamationmark.triangle": "warning",
  "exclamationmark.triangle.fill": "warning",
  "exclamationmark.octagon.fill": "report",
  "doc.fill": "description",
  "doc.on.doc.fill": "content-copy",
  "hand.raised.fill": "front-hand",
  "pause.circle.fill": "pause-circle",
  "list.clipboard.fill": "assignment",
};

interface IconSymbolProps {
  name: IconSymbolName;
  size?: number;
  color: string | OpaqueColorValue;
  style?: StyleProp<TextStyle>;
}

export function IconSymbol({ name, size = 24, color, style }: IconSymbolProps) {
  return (
    <MaterialIcons
      name={MAPPING[name]}
      size={size}
      color={color}
      style={style}
    />
  );
}
