import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { OpaqueColorValue, type StyleProp, type TextStyle } from "react-native";

export type IconSymbolName =
  | "radio"
  | "map-pin"
  | "flag"
  | "user"
  | "user-check"
  | "file-text"
  | "box"
  | "wallet"
  | "house.fill"
  | "ticket.fill"
  | "fork.knife"
  | "chart.line.uptrend.xyaxis"
  | "person.crop.circle.fill"
  | "eye.fill"
  | "eye.slash.fill"
  | "paperplane.fill"
  | "chevron.left.forwardslash.chevron.right"
  | "chevron.right"
  | "chevron.left"
  | "chevron.down"
  | "chevron.up"
  | "info.circle"
  | "cloud.upload"
  | "camera.fill"
  | "check"
  | "circle.fill"
  | "map.marker"
  | "location.fill"
  | "arrow.up.left.and.arrow.down.right"
  | "xmark"
  | "map.fill"
  | "lock.fill"
  | "pencil"
  | "trash"
  | "plus"
  | "fullscreen"
  | "send"
  | "home"
  | "restaurant"
  | "notifications"
  | "logout"
  | "chat"
  | "icon"
  | "menu"
  | "users"
  | "power"
  | "arrow.right"
  | "arrow.left"
  | "arrow-left"
  | "arrow-right"
  | "arrow-u-turn-left"
  | "arrow-u-turn-right"
  | "arrow.up"
  | "arrow-up"
  | "settings"
  | "bell"
  | "list"
  | "dollar-sign"
  | "info"
  | "headphones"
  | "play"
  | "activity"
  | "lightbulb"
  | "shield"
  | "close"
  | "edit"
  | "delete"
  | "add"
  | "share"
  | "file-text"
  | "credit-card"
  | "location"
  | "shopping-bag"
  | "truck"
  | "moon"
  | "log-out"
  | "alert-circle"
  | "calender"
  | "clock.fill"
  | "touchid"
  | "1.circle.fill"
  | "2.circle.fill"
  | "checkmark.circle.fill"
  | "circle"
  | "arrow.down"
  | "location.on"
  | "map"
  | "storefront"
  | "person.circle"
  | "bag"
  | "package"
  | "arrow.clockwise"
  | "pizza"
  | "p.square"
  | "d.square"
  | "clock"
  | "arrow.right.circle"
  | "note"
  | "phone"
  | "checkmark"
  | "navigation"
  | "person"
  | "checkmark.seal"
  | "star.fill"
  | "person.text.rectangle"
  | "doc.text"
  | "creditcard"
  | "car"
  | "box.truck"
  | "calendar"
  | "person.fill"
  | "bus.fill"
  | "car.fill"
  | "square.grid.2x2.fill"
  | "shippingbox.fill"
  | "apple.logo"
  | "google.logo"
  | "search"
  | "gearshape.fill"
  | "box.fill"
  | "alert-triangle"
  | "message-square"
  | "mail"
  | "x"
  | "cart"
  | "star"
  | "heart"
  | "banknote"
  | "checkmark.circle"
  | "exclamationmark"
  | "exclamationmark.triangle"
  | "magnifyingglass"
  | "mappin"
  | "message.fill"
  | "number"
  | "phone.fill"
  | "slider.horizontal.3"
  | "xmark.circle"
  | "building.columns"
  | "xmark.circle.fill"
  | "doc.on.doc";

export const MAPPING: Record<
  IconSymbolName,
  keyof typeof MaterialIcons.glyphMap
> = {
  location: "location-on",
  "shopping-bag": "shopping-bag",
  truck: "local-shipping",
  moon: "dark-mode",
  "log-out": "logout",
  "house.fill": "home",
  "ticket.fill": "confirmation-number",
  "fork.knife": "restaurant",
  "chart.line.uptrend.xyaxis": "show-chart",
  "person.crop.circle.fill": "account-circle",
  "eye.fill": "remove-red-eye",
  "eye.slash.fill": "visibility-off",
  "paperplane.fill": "send",
  send: "send",
  "chevron.left.forwardslash.chevron.right": "code",
  "chevron.right": "chevron-right",
  "chevron.left": "chevron-left",
  "chevron.down": "keyboard-arrow-down",
  "chevron.up": "keyboard-arrow-up",
  "info.circle": "info",
  "cloud.upload": "cloud-upload",
  "camera.fill": "photo-camera",
  check: "check",
  "circle.fill": "radio-button-checked",
  "map.marker": "place",
  "location.fill": "location-on",
  "map.fill": "map",
  "arrow.up.left.and.arrow.down.right": "fullscreen",
  fullscreen: "fullscreen",
  xmark: "close",
  "lock.fill": "lock",
  pencil: "edit",
  trash: "delete",
  plus: "add",
  home: "home",
  restaurant: "restaurant",
  notifications: "notifications",
  logout: "logout",
  chat: "chat",
  icon: "help",
  menu: "menu",
  users: "people",
  power: "power",
  "arrow.right": "arrow-forward",
  "arrow.left": "arrow-back",
  "arrow.up": "arrow-upward",
  "arrow-up": "arrow-upward",
  "arrow-u-turn-left": "undo",
  "arrow-u-turn-right": "redo",
  "arrow-left": "arrow-left",
  "arrow-right": "arrow-right",
  settings: "settings",
  bell: "notifications",
  list: "list",
  "dollar-sign": "attach-money",
  info: "info",
  headphones: "headset",
  play: "play-arrow",
  activity: "show-chart",
  close: "close",
  edit: "edit",
  delete: "delete",
  shield: "security",
  lightbulb: "lightbulb",
  share: "share",
  "file-text": "description",
  "credit-card": "credit-card",
  "alert-circle": "error-outline",
  calender: "calendar-today",
  "clock.fill": "access-time",
  touchid: "fingerprint",
  "1.circle.fill": "looks-one",
  "2.circle.fill": "looks-two",
  "checkmark.circle.fill": "check-circle",
  circle: "radio-button-unchecked",
  "arrow.down": "arrow-downward",
  "location.on": "my-location",
  map: "map",
  storefront: "storefront",
  "person.circle": "person",
  bag: "work",
  package: "inventory",
  "arrow.clockwise": "rotate-right",
  add: "add",
  pizza: "local-pizza",
  "p.square": "crop-square",
  "d.square": "crop-square",
  clock: "access-time",
  "arrow.right.circle": "arrow-forward-ios",
  note: "note",
  phone: "phone",
  checkmark: "check",
  navigation: "navigation",
  person: "person",
  "checkmark.seal": "check-circle",
  "star.fill": "star",
  "person.text.rectangle": "badge",
  "doc.text": "article",
  creditcard: "credit-card",
  car: "directions-car",
  "box.truck": "local-shipping",
  calendar: "calendar-today",
  "person.fill": "person",
  "bus.fill": "directions-bus",
  "car.fill": "directions-car",
  "square.grid.2x2.fill": "grid-view",
  "shippingbox.fill": "inventory",
  "apple.logo": "apple",
  "google.logo": "g-translate",
  search: "search",
  "gearshape.fill": "settings",
  "box.fill": "inventory",
  radio: "radio-button-checked",
  "map-pin": "place",
  flag: "flag",
  user: "person",
  "user-check": "verified-user",
  box: "inventory",
  wallet: "account-balance-wallet",
  "message-square": "sms",
  mail: "email",
  "alert-triangle": "warning",
  x: "close",
  cart: "shopping-cart",
  star: "star",
  heart: "monitor-heart",
  banknote: "payments",
  "checkmark.circle": "check-circle-outline",
  exclamationmark: "priority-high",
  "exclamationmark.triangle": "warning",
  magnifyingglass: "search",
  mappin: "place",
  "message.fill": "message",
  number: "tag",
  "phone.fill": "phone",
  "slider.horizontal.3": "tune",
  "xmark.circle": "cancel",
  "building.columns": "account-balance",
  "xmark.circle.fill": "cancel",
  "doc.on.doc": "content-copy",
};

interface IconSymbolProps {
  name: IconSymbolName;
  size?: number;
  color: string | OpaqueColorValue;
  style?: StyleProp<TextStyle>;
}

export function IconSymbol({ name, size = 24, color, style }: IconSymbolProps) {
  return (
    <MaterialIcons
      name={MAPPING[name] as keyof typeof MaterialIcons.glyphMap}
      size={size}
      color={color}
      style={style}
    />
  );
}
