import { Notification } from "@/types/notification";

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "1",
    type: "orders",
    title: "New Order #12345",
    timestamp: "2 min ago",
    summary: "Customer John D. ordered 2x Burger, 1x Fries",
    actionLabel: "View Order",
    actionCallback: () => console.log("View Order clicked"),
  },
  {
    id: "2",
    type: "payouts",
    title: "Payout Processed",
    timestamp: "5 min ago",
    summary: "Your payout of $120.50 has been sent to your bank",
  },
  {
    id: "3",
    type: "system",
    title: "App Update Available",
    timestamp: "10 min ago",
    summary: "Version 2.1.0 with bug fixes and performance improvements",
  },
  {
    id: "4",
    type: "orders",
    title: "New Order #12346",
    timestamp: "12 min ago",
    summary: "Customer Sarah K. ordered 1x Salad, 1x Lemonade",
    actionLabel: "View Order",
    actionCallback: () => console.log("View Order clicked"),
  },
  {
    id: "5",
    type: "payouts",
    title: "Payout Failed",
    timestamp: "20 min ago",
    summary:
      "Your payout of $250.00 could not be processed. Please update your bank info.",
  },
  {
    id: "6",
    type: "system",
    title: "Maintenance Scheduled",
    timestamp: "30 min ago",
    summary: "System maintenance will occur at 2:00 AM UTC",
  },
  {
    id: "7",
    type: "orders",
    title: "New Order #12347",
    timestamp: "35 min ago",
    summary: "Customer Alex P. ordered 3x Pizza",
    actionLabel: "View Order",
    actionCallback: () => console.log("View Order clicked"),
  },
  {
    id: "8",
    type: "orders",
    title: "Order #12344 Delivered",
    timestamp: "40 min ago",
    summary: "Customer Maria L. confirmed delivery",
    actionLabel: "View Order",
    actionCallback: () => console.log("View Order clicked"),
  },
  {
    id: "9",
    type: "payouts",
    title: "Payout Pending",
    timestamp: "50 min ago",
    summary: "Your payout of $80.75 is being processed",
  },
  {
    id: "10",
    type: "system",
    title: "Security Alert",
    timestamp: "1 hr ago",
    summary: "New login detected from an unrecognized device",
  },
  {
    id: "11",
    type: "orders",
    title: "New Order #12348",
    timestamp: "1 hr 5 min ago",
    summary: "Customer Liam T. ordered 2x Sushi Rolls",
    actionLabel: "View Order",
    actionCallback: () => console.log("View Order clicked"),
  },
  {
    id: "12",
    type: "payouts",
    title: "Payout Processed",
    timestamp: "1 hr 20 min ago",
    summary: "Your payout of $300.00 has been sent to your bank",
  },
  {
    id: "13",
    type: "system",
    title: "New Feature Released",
    timestamp: "1 hr 30 min ago",
    summary: "Check out our new dashboard analytics feature",
  },
  {
    id: "14",
    type: "orders",
    title: "Order #12349 Cancelled",
    timestamp: "1 hr 45 min ago",
    summary: "Customer Emma W. cancelled their order",
    actionLabel: "View Order",
    actionCallback: () => console.log("View Order clicked"),
  },
  {
    id: "15",
    type: "orders",
    title: "New Order #12350",
    timestamp: "2 hr ago",
    summary: "Customer Noah G. ordered 1x Latte, 2x Muffins",
    actionLabel: "View Order",
    actionCallback: () => console.log("View Order clicked"),
  },
  {
    id: "16",
    type: "payouts",
    title: "Payout Failed",
    timestamp: "2 hr 15 min ago",
    summary:
      "Your payout of $50.00 could not be processed due to network error",
  },
  {
    id: "17",
    type: "system",
    title: "Terms of Service Updated",
    timestamp: "2 hr 30 min ago",
    summary: "Please review our updated terms of service",
  },
  {
    id: "18",
    type: "orders",
    title: "New Order #12351",
    timestamp: "2 hr 45 min ago",
    summary: "Customer Olivia H. ordered 4x Sandwiches",
    actionLabel: "View Order",
    actionCallback: () => console.log("View Order clicked"),
  },
  {
    id: "19",
    type: "payouts",
    title: "Payout Processed",
    timestamp: "3 hr ago",
    summary: "Your payout of $90.25 has been sent to your bank",
  },
  {
    id: "20",
    type: "system",
    title: "Scheduled Downtime Completed",
    timestamp: "3 hr 15 min ago",
    summary: "Maintenance completed successfully, system fully operational",
  },
];
