import { Category, MenuItem } from "@/types/menu";

export const INITIAL_CATEGORIES: Category[] = [
  { id: "1", name: "Rice" },
  { id: "2", name: "Proteins" },
  { id: "3", name: "Cloths" },
  { id: "4", name: "Wigs" },
  { id: "5", name: "Snacks" },
  { id: "6", name: "Drinks" },
  { id: "7", name: "Vegetables" },
  { id: "8", name: "Desserts" },
];

export const INITIAL_ITEMS: MenuItem[] = [
  {
    id: "1",
    name: "Jollof Rice",
    price: 2500,
    inStock: true,
    category: "Rice",
    images: ["https://picsum.photos/200"],
  },
  {
    id: "2",
    name: "Fried Chicken",
    price: 3000,
    inStock: false,
    category: "Proteins",
    images: ["https://picsum.photos/201"],
  },
  {
    id: "3",
    name: "Beef Suya",
    price: 1500,
    inStock: true,
    category: "Proteins",
    images: ["https://picsum.photos/202"],
  },
  {
    id: "4",
    name: "Eba and Egusi",
    price: 2000,
    inStock: true,
    category: "Rice",
    images: ["https://picsum.photos/203"],
  },
  {
    id: "5",
    name: "Moi Moi",
    price: 1200,
    inStock: false,
    category: "Snacks",
    images: ["https://picsum.photos/204"],
  },
  {
    id: "6",
    name: "Coca Cola",
    price: 500,
    inStock: true,
    category: "Drinks",
    images: ["https://picsum.photos/205"],
  },
  {
    id: "7",
    name: "Fried Plantain",
    price: 800,
    inStock: true,
    category: "Snacks",
    images: ["https://picsum.photos/206"],
  },
  {
    id: "8",
    name: "Vegetable Soup",
    price: 2200,
    inStock: true,
    category: "Vegetables",
    images: ["https://picsum.photos/207"],
  },
  {
    id: "9",
    name: "Chocolate Cake",
    price: 1800,
    inStock: false,
    category: "Desserts",
    images: ["https://picsum.photos/208"],
  },
  {
    id: "10",
    name: "Orange Juice",
    price: 700,
    inStock: true,
    category: "Drinks",
    images: ["https://picsum.photos/209"],
  },
  {
    id: "11",
    name: "Ankara Dress",
    price: 5000,
    inStock: true,
    category: "Cloths",
    images: ["https://picsum.photos/210"],
  },
  {
    id: "12",
    name: "Lace Wig",
    price: 8000,
    inStock: false,
    category: "Wigs",
    images: ["https://picsum.photos/211"],
  },
];
