import { Order } from "@/types/order";

const now = Date.now();

// Mock data - 25 orders
export const MOCK_ORDERS: Order[] = [
  {
    id: "1",
    customerName: "Sarah J.",
    customerProfile: "https://picsum.photos/50/50?random=1",
    items: [
      { id: "1", name: "Classic Burger", quantity: 1 },
      { id: "2", name: "Large Fries", quantity: 1 },
    ],
    total: 1250,
    status: "pending",
    countdown: "04:30 left",
    deadline: now + 4 * 60 * 1000 + 30 * 1000,
  },
  {
    id: "2",
    customerName: "Mark T.",
    customerProfile: "https://picsum.photos/50/50?random=2",
    items: [{ id: "3", name: "Pizza", quantity: 2 }],
    total: 2500,
    status: "active",
    countdown: "10:00 left",
  },
  {
    id: "3",
    customerName: "Linda K.",
    customerProfile: "https://picsum.photos/50/50?random=3",
    items: [{ id: "4", name: "Fried Rice", quantity: 1 }],
    total: 1500,
    status: "completed",
  },
  {
    id: "4",
    customerName: "James P.",
    customerProfile: "https://picsum.photos/50/50?random=4",
    items: [
      { id: "5", name: "Jollof Rice", quantity: 2 },
      { id: "6", name: "Grilled Chicken", quantity: 1 },
    ],
    total: 3200,
    status: "pending",
    countdown: "05:15 left",
    deadline: now + 4 * 60 * 1000 + 30 * 1000,
  },
  {
    id: "5",
    customerName: "Emily R.",
    customerProfile: "https://picsum.photos/50/50?random=5",
    items: [{ id: "7", name: "Beef Burger", quantity: 1 }],
    total: 1200,
    status: "active",
    countdown: "08:45 left",
  },
  {
    id: "6",
    customerName: "Daniel L.",
    customerProfile: "https://picsum.photos/50/50?random=6",
    items: [
      { id: "8", name: "Pizza", quantity: 1 },
      { id: "9", name: "Coke", quantity: 2 },
    ],
    total: 2100,
    status: "completed",
  },
  {
    id: "7",
    customerName: "Olivia H.",
    customerProfile: "https://picsum.photos/50/50?random=7",
    items: [{ id: "10", name: "Fries", quantity: 3 }],
    total: 900,
    status: "pending",
    countdown: "03:50 left",
    deadline: now + 4 * 60 * 1000 + 30 * 1000,
  },
  {
    id: "8",
    customerName: "Michael B.",
    customerProfile: "https://picsum.photos/50/50?random=8",
    items: [{ id: "11", name: "Chicken Wrap", quantity: 2 }],
    total: 2000,
    status: "active",
    countdown: "12:20 left",
  },
  {
    id: "9",
    customerName: "Sophia G.",
    customerProfile: "https://picsum.photos/50/50?random=9",
    items: [{ id: "12", name: "Fish & Chips", quantity: 1 }],
    total: 1800,
    status: "completed",
  },
  {
    id: "10",
    customerName: "David M.",
    customerProfile: "https://picsum.photos/50/50?random=10",
    items: [
      { id: "13", name: "Spaghetti", quantity: 2 },
      { id: "14", name: "Garlic Bread", quantity: 1 },
    ],
    total: 2800,
    status: "pending",
    countdown: "06:00 left",
  },
  {
    id: "11",
    customerName: "Grace C.",
    customerProfile: "https://picsum.photos/50/50?random=11",
    items: [{ id: "15", name: "Salad", quantity: 1 }],
    total: 900,
    status: "active",
    countdown: "09:10 left",
  },
  {
    id: "12",
    customerName: "Henry F.",
    customerProfile: "https://picsum.photos/50/50?random=12",
    items: [{ id: "16", name: "Beef Steak", quantity: 1 }],
    total: 3500,
    status: "completed",
  },
  {
    id: "13",
    customerName: "Isabella D.",
    customerProfile: "https://picsum.photos/50/50?random=13",
    items: [{ id: "17", name: "Chicken Burger", quantity: 2 }],
    total: 2400,
    status: "pending",
    countdown: "07:15 left",
  },
  {
    id: "14",
    customerName: "Jack R.",
    customerProfile: "https://picsum.photos/50/50?random=14",
    items: [{ id: "18", name: "Veggie Pizza", quantity: 1 }],
    total: 2200,
    status: "active",
    countdown: "11:40 left",
  },
  {
    id: "15",
    customerName: "Lily S.",
    customerProfile: "https://picsum.photos/50/50?random=15",
    items: [{ id: "19", name: "Ice Cream", quantity: 3 }],
    total: 1500,
    status: "completed",
  },
  {
    id: "16",
    customerName: "Nathan K.",
    customerProfile: "https://picsum.photos/50/50?random=16",
    items: [{ id: "20", name: "Chocolate Cake", quantity: 1 }],
    total: 1800,
    status: "pending",
    countdown: "05:40 left",
  },
  {
    id: "17",
    customerName: "Olivia P.",
    customerProfile: "https://picsum.photos/50/50?random=17",
    items: [
      { id: "21", name: "Chicken Wings", quantity: 6 },
      { id: "22", name: "Coke", quantity: 2 },
    ],
    total: 2200,
    status: "active",
    countdown: "10:50 left",
  },
  {
    id: "18",
    customerName: "Patrick N.",
    customerProfile: "https://picsum.photos/50/50?random=18",
    items: [{ id: "23", name: "Burger Meal", quantity: 1 }],
    total: 1500,
    status: "completed",
  },
  {
    id: "19",
    customerName: "Quinn O.",
    customerProfile: "https://picsum.photos/50/50?random=19",
    items: [{ id: "24", name: "Sushi", quantity: 2 }],
    total: 3200,
    status: "pending",
    countdown: "06:30 left",
  },
  {
    id: "20",
    customerName: "Rachel H.",
    customerProfile: "https://picsum.photos/50/50?random=20",
    items: [{ id: "25", name: "Pasta", quantity: 1 }],
    total: 1400,
    status: "active",
    countdown: "09:00 left",
  },
  {
    id: "21",
    customerName: "Steve J.",
    customerProfile: "https://picsum.photos/50/50?random=21",
    items: [{ id: "26", name: "Chicken Sandwich", quantity: 2 }],
    total: 2000,
    status: "completed",
  },
  {
    id: "22",
    customerName: "Tina M.",
    customerProfile: "https://picsum.photos/50/50?random=22",
    items: [{ id: "27", name: "Cheese Pizza", quantity: 1 }],
    total: 2100,
    status: "pending",
    countdown: "07:50 left",
  },
  {
    id: "23",
    customerName: "Uma L.",
    customerProfile: "https://picsum.photos/50/50?random=23",
    items: [{ id: "28", name: "Chocolate Muffin", quantity: 3 }],
    total: 1200,
    status: "active",
    countdown: "12:10 left",
  },
  {
    id: "24",
    customerName: "Victor C.",
    customerProfile: "https://picsum.photos/50/50?random=24",
    items: [{ id: "29", name: "Taco", quantity: 2 }],
    total: 1800,
    status: "completed",
  },
  {
    id: "25",
    customerName: "Wendy A.",
    customerProfile: "https://picsum.photos/50/50?random=25",
    items: [{ id: "30", name: "Beef Wrap", quantity: 1 }],
    total: 1500,
    status: "pending",
    countdown: "04:10 left",
  },
];
